// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfqgzjltymvyghanwtpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmcWd6amx0eW12eWdoYW53dHB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0MTA1NjksImV4cCI6MjA1Mzk4NjU2OX0.IPdloCZmrjkx0rgeUYzPWrbmi0VQWRJ_SHrLa7Xt4wY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);